# ---- main ----
MASCOTAS_INICIALES = 6

# ---- hotel ----
MAXIMO_ENERGIA_HOTEL = 100

# -- métodos hotel --
COSTO_ENERGIA_PASEAR = 20
COSTO_ENERGIA_ALIMENTAR = 10
MASCOTA_SATISFACCION_MINIMO = 30

# ---- mascotas ----
ENTRETENCION_PASEAR = 30
SACIEDAD_PASEAR = -10